# Form implementation generated from reading ui file 'GraderProject.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(225, 260)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.StudentInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.StudentInput.setGeometry(QtCore.QRect(150, 10, 41, 20))
        self.StudentInput.setObjectName("StudentInput")
        self.StudentLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.StudentLabel.setGeometry(QtCore.QRect(10, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.StudentLabel.setFont(font)
        self.StudentLabel.setObjectName("StudentLabel")
        self.ScoresInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ScoresInput.setGeometry(QtCore.QRect(150, 40, 41, 20))
        self.ScoresInput.setObjectName("ScoresInput")
        self.ScoresLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.ScoresLabel.setGeometry(QtCore.QRect(10, 40, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ScoresLabel.setFont(font)
        self.ScoresLabel.setObjectName("ScoresLabel")
        self.ErrorLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.ErrorLabel.setGeometry(QtCore.QRect(20, 220, 201, 21))
        self.ErrorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ErrorLabel.setObjectName("ErrorLabel")
        self.SubmitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SubmitButton.setGeometry(QtCore.QRect(90, 190, 56, 17))
        self.SubmitButton.setObjectName("SubmitButton")
        self.Score1Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Score1Label.setGeometry(QtCore.QRect(20, 75, 81, 21))
        self.Score1Label.setObjectName("Score1Label")
        self.Score1Input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Score1Input.setGeometry(QtCore.QRect(150, 75, 41, 20))
        self.Score1Input.setObjectName("Score1Input")
        self.Score2Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Score2Label.setGeometry(QtCore.QRect(20, 105, 81, 21))
        self.Score2Label.setObjectName("Score2Label")
        self.Score3Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Score3Label.setGeometry(QtCore.QRect(20, 135, 81, 21))
        self.Score3Label.setObjectName("Score3Label")
        self.Score4Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Score4Label.setGeometry(QtCore.QRect(20, 165, 81, 21))
        self.Score4Label.setObjectName("Score4Label")
        self.Score2Input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Score2Input.setGeometry(QtCore.QRect(150, 105, 41, 20))
        self.Score2Input.setObjectName("Score2Input")
        self.Score3Input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Score3Input.setGeometry(QtCore.QRect(150, 135, 41, 20))
        self.Score3Input.setObjectName("Score3Input")
        self.Score4Input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Score4Input.setGeometry(QtCore.QRect(150, 165, 41, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Score4Input.sizePolicy().hasHeightForWidth())
        self.Score4Input.setSizePolicy(sizePolicy)
        self.Score4Input.setObjectName("Score4Input")
        self.AttemptsConfirm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.AttemptsConfirm.setGeometry(QtCore.QRect(200, 40, 21, 21))
        self.AttemptsConfirm.setObjectName("AttemptsConfirm")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grader"))
        self.StudentLabel.setText(_translate("MainWindow", "Student Name:"))
        self.ScoresLabel.setText(_translate("MainWindow", "Number of Attempts:"))
        self.ErrorLabel.setText(_translate("MainWindow", "Error Message"))
        self.SubmitButton.setText(_translate("MainWindow", "Submit"))
        self.Score1Label.setText(_translate("MainWindow", "Score 1:"))
        self.Score2Label.setText(_translate("MainWindow", "Score 2:"))
        self.Score3Label.setText(_translate("MainWindow", "Score 3:"))
        self.Score4Label.setText(_translate("MainWindow", "Score 4:"))
        self.AttemptsConfirm.setText(_translate("MainWindow", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
